### ISSUE TITLE
update notebook to use new cloud object storage

### ISSUE THREAD

**Issue by chenjgui** [IBM/watson-nao-robot#17]
i creat a project in Watson Studio,but i can't find **Object Storage**,it just have **Cloud  Object Storage**
what should i do?
![image](https://user-images.githubusercontent.com/38098233/38466913-324f5da2-3b63-11e8-8a7e-3b4dd06d0ef4.png)
![image](https://user-images.githubusercontent.com/38098233/38466920-50eada66-3b63-11e8-87ed-5783b82474f5.png)
I am a beginner and I thank you very much for any help.

**Comment by chenjgui** [comment]
and i use Cloud Object Storage ,but i can't run jupyter notebook successful in next step.

**Comment by stevemar** [comment]
@chenjgui thanks for creating the issue. @RK-Sharath this code pattern should be updated to use the new cloud object service (not the swift based one).

The file https://github.com/IBM/watson-nao-robot/blob/master/Notebook/Robo_Notebook.ipynb should be updated like this one was: https://github.com/IBM/pixiedust-facebook-analysis/commit/b22714ae37afa8084d3565b3b92b20ee8d44c0f2 -- as well as the instructions in the README. 

If i recall correctly, @balajikadambi has updated a few notebooks already, suggest pinging him to get a better understanding.

**Comment by RK-Sharath** [comment]
@stevemart This is complete. Please review.

**Comment by stevemar** [comment]
@RK-Sharath please use branches and pull requests to make reviewing easier. I looked at the last few commits, specifically https://github.com/IBM/watson-nao-robot/commit/5765cd5755160d178abc7537da5d6ba1d66e18a7 and it looks like all the object storage bits was removed, is that intentional? Did we not need them before?

If they're not needed then please remove the references to the new python libraries, like `pip install ibm-cos-sdk` and `"import ibm_boto3\n", "from botocore.client import Config\n"` and the step `### Create Object Storage Service` since the user doesn't actually do anything there and no code is run.

**Comment by RK-Sharath** [comment]
@stevemart I have submitted a pull request after making the changes suggested by you. The object storage has been removed intentionally to keep it simple. The object storage might be useful if we are reading more than one file but in this pattern there's only one data file.

**Comment by stevemar** [comment]
Awesome, thanks for the explanation @RK-Sharath. I'm reviewing the PR now.

**Comment by stevemar** [comment]
@RK-Sharath i created PR https://github.com/IBM/watson-nao-robot/pull/19/files -- please review. I will now close this issue, i believe it's fully addressed. @chenjgui please try to work through the instructions again.
